improve private-zone module
alibabacloud-automation/terraform-alicloud-private-zone pull request #3
Opened 2020-02-07 03:55 UTC by zql-tqy

2020-02-07 09:39 UTC, xiaozhu36 requested changes

2020-02-07 09:39 UTC, xiaozhu36 commented on variables.tf
> +  description = "PVT Zone record list.Each item can contains keys: 'resource_record'(The resource record of the Private Zone Record.),'type'(The type of the Private Zone Record. Valid values: A, CNAM
record_list 改成 records，但是要对record_list做下兼容

2020-02-07 09:39 UTC, xiaozhu36 commented on variables.tf
> +  description = "The id List of the VPC with the same region, for example:['vpc-1','vpc-2']."
vpc_id_list 改成 vpc_ids，但是要对vpc_id_list做下兼容

2020-02-07 09:39 UTC, xiaozhu36 commented on variables.tf
> +  description = ""
add_records

2020-02-07 09:39 UTC, xiaozhu36 commented on modules/multi_record/variables.tf
> +variable "region" {
没必要用子module

2020-02-07 09:39 UTC, xiaozhu36 commented on examples/multi_record/main.tf
> +module "multi_record" {
example和子module的目录名用-不是_

2020-02-10 01:51 UTC, Rich-yi commented on examples/complete/README.md
> +## Outputs
example中的readme不用写outputs吧

2020-02-10 01:51 UTC, Rich-yi commented on examples/complete/main.tf
> +  vpc_ids   = ["vpc-uf61gzxodh2w60l9nk4mm"]
vpc-uf61gzxodh2w60l9nk4mm改成vpc-uf61gzxodxxxxxxxxx

2020-02-10 01:51 UTC, Rich-yi commented on examples/complete/outputs.tf
> +output "this_zone_records" {
this_zone-xxxx改成this_private_zone_xxx

2020-02-10 01:51 UTC, Rich-yi commented on main.tf
> +}
格式化

2020-02-10 01:51 UTC, Rich-yi commented on outputs.tf
> +output "this_zone_records" {
一样改成this_private_zone_Xxx

2020-02-10 03:15 UTC, Rich-yi commented on CHANGELOG.md
> +-update the module to the format of the new version [GH-2]( https://github.com/terraform-alicloud-modules/terraform-alicloud-private-zone/pull/2)
“-”后面要空格

2020-02-10 03:15 UTC, Rich-yi commented on examples/complete/README.md
> +| this_zone_name | The name of Private Zone |
如果需要写，和outputs.tf文件中保持一致

2020-02-10 03:15 UTC, Rich-yi commented on main.tf
> +  attach_vpc  = var.existing_zone_name != "" || var.create ? true : false
这两个判断逻辑不是一样的吗？保留一个就行了吧

2020-02-10 06:47 UTC, xiaozhu36 requested changes

2020-02-10 06:47 UTC, xiaozhu36 commented on README-CN.md
> +Terraform模块用于在阿里云上创建 Private Zone，同时您可以为 Zone 添加 records 并关联 VPC。
Private Zone 这个地方给一个产品的地址

2020-02-10 06:47 UTC, xiaozhu36 commented on README-CN.md
> +本 Module 要求使用 Terraform 0.12 和 阿里云 Provider 1.62.1+。
这个地方为啥要 1.62.1+

2020-02-10 06:47 UTC, xiaozhu36 commented on README.md
>  * [PVTZ Records](https://www.terraform.io/docs/providers/alicloud/d/pvtz_zone_records.html)
这几个地址是错的，应该是resource的地址

2020-02-10 06:47 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  vpc_ids   = ["vpc-uf61gzxodh2w60l9n****"]
example中要么用vpc的data source，要么用 vpc的module创建一个新的，不要用一个假的

2020-02-10 06:47 UTC, xiaozhu36 commented on main.tf
>  }
这个地方为啥要用datasource

2020-02-10 06:47 UTC, xiaozhu36 commented on outputs.tf
> +  value       = [flatten(alicloud_pvtz_zone.this.*.name)]
这个应该只有一个吧，所以不用flatten，直接用concat取第一个就行

2020-02-10 08:37 UTC, xiaozhu36 approved these changes

2020-02-10 08:38 UTC, merged